### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LvckyAPI** [uhmarlon/Teamspeak-Support-Bot#1]
https://prnt.sc/vgulzh

**Comment by uhmarlon** [comment]
Please do not use a subchannel try it with a main channel with information

**Comment by SinoX1337** [comment]
Oh thanks! you fixed my problem uhmarlon.

**Comment by LvckyAPI** [comment]
Danke für die Hilfe UHhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhMAAAAAAAAAAAAAARLOOOON
Thank you very much lul
